/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as BoardingPassRouteImport } from './routes/boarding-pass'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as CheckinIndexRouteImport } from './routes/checkin.index'
import { Route as CheckinSeatsRouteImport } from './routes/checkin.seats'
import { Route as CheckinReviewRouteImport } from './routes/checkin.review'
import { Route as CheckinPassengersRouteImport } from './routes/checkin.passengers'
import { Route as CheckinConfirmationRouteImport } from './routes/checkin.confirmation'
import { Route as CheckinAddonsRouteImport } from './routes/checkin.addons'
import { Route as AuthSignupRouteImport } from './routes/auth.signup'
import { Route as AuthPnrRouteImport } from './routes/auth.pnr'
import { Route as AuthOtpRouteImport } from './routes/auth.otp'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'

const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const BoardingPassRoute = BoardingPassRouteImport.update({
  id: '/boarding-pass',
  path: '/boarding-pass',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const CheckinIndexRoute = CheckinIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CheckinRoute,
} as any)
const CheckinSeatsRoute = CheckinSeatsRouteImport.update({
  id: '/seats',
  path: '/seats',
  getParentRoute: () => CheckinRoute,
} as any)
const CheckinReviewRoute = CheckinReviewRouteImport.update({
  id: '/review',
  path: '/review',
  getParentRoute: () => CheckinRoute,
} as any)
const CheckinPassengersRoute = CheckinPassengersRouteImport.update({
  id: '/passengers',
  path: '/passengers',
  getParentRoute: () => CheckinRoute,
} as any)
const CheckinConfirmationRoute = CheckinConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => CheckinRoute,
} as any)
const CheckinAddonsRoute = CheckinAddonsRouteImport.update({
  id: '/addons',
  path: '/addons',
  getParentRoute: () => CheckinRoute,
} as any)
const AuthSignupRoute = AuthSignupRouteImport.update({
  id: '/auth/signup',
  path: '/auth/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthPnrRoute = AuthPnrRouteImport.update({
  id: '/auth/pnr',
  path: '/auth/pnr',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/auth/forgot',
  path: '/auth/forgot',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/boarding-pass': typeof BoardingPassRoute
  '/checkin': typeof CheckinRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/pnr': typeof AuthPnrRoute
  '/auth/signup': typeof AuthSignupRoute
  '/checkin/addons': typeof CheckinAddonsRoute
  '/checkin/confirmation': typeof CheckinConfirmationRoute
  '/checkin/passengers': typeof CheckinPassengersRoute
  '/checkin/review': typeof CheckinReviewRoute
  '/checkin/seats': typeof CheckinSeatsRoute
  '/checkin/': typeof CheckinIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/boarding-pass': typeof BoardingPassRoute
  '/notifications': typeof NotificationsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/pnr': typeof AuthPnrRoute
  '/auth/signup': typeof AuthSignupRoute
  '/checkin/addons': typeof CheckinAddonsRoute
  '/checkin/confirmation': typeof CheckinConfirmationRoute
  '/checkin/passengers': typeof CheckinPassengersRoute
  '/checkin/review': typeof CheckinReviewRoute
  '/checkin/seats': typeof CheckinSeatsRoute
  '/checkin': typeof CheckinIndexRoute
  '/dashboard': typeof DashboardIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/boarding-pass': typeof BoardingPassRoute
  '/checkin': typeof CheckinRouteWithChildren
  '/dashboard': typeof DashboardRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/pnr': typeof AuthPnrRoute
  '/auth/signup': typeof AuthSignupRoute
  '/checkin/addons': typeof CheckinAddonsRoute
  '/checkin/confirmation': typeof CheckinConfirmationRoute
  '/checkin/passengers': typeof CheckinPassengersRoute
  '/checkin/review': typeof CheckinReviewRoute
  '/checkin/seats': typeof CheckinSeatsRoute
  '/checkin/': typeof CheckinIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boarding-pass'
    | '/checkin'
    | '/dashboard'
    | '/notifications'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/pnr'
    | '/auth/signup'
    | '/checkin/addons'
    | '/checkin/confirmation'
    | '/checkin/passengers'
    | '/checkin/review'
    | '/checkin/seats'
    | '/checkin/'
    | '/dashboard/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/boarding-pass'
    | '/notifications'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/pnr'
    | '/auth/signup'
    | '/checkin/addons'
    | '/checkin/confirmation'
    | '/checkin/passengers'
    | '/checkin/review'
    | '/checkin/seats'
    | '/checkin'
    | '/dashboard'
  id:
    | '__root__'
    | '/'
    | '/boarding-pass'
    | '/checkin'
    | '/dashboard'
    | '/notifications'
    | '/auth/forgot'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/pnr'
    | '/auth/signup'
    | '/checkin/addons'
    | '/checkin/confirmation'
    | '/checkin/passengers'
    | '/checkin/review'
    | '/checkin/seats'
    | '/checkin/'
    | '/dashboard/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BoardingPassRoute: typeof BoardingPassRoute
  CheckinRoute: typeof CheckinRouteWithChildren
  DashboardRoute: typeof DashboardRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  AuthForgotRoute: typeof AuthForgotRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthPnrRoute: typeof AuthPnrRoute
  AuthSignupRoute: typeof AuthSignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boarding-pass': {
      id: '/boarding-pass'
      path: '/boarding-pass'
      fullPath: '/boarding-pass'
      preLoaderRoute: typeof BoardingPassRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/checkin/': {
      id: '/checkin/'
      path: '/'
      fullPath: '/checkin/'
      preLoaderRoute: typeof CheckinIndexRouteImport
      parentRoute: typeof CheckinRoute
    }
    '/checkin/seats': {
      id: '/checkin/seats'
      path: '/seats'
      fullPath: '/checkin/seats'
      preLoaderRoute: typeof CheckinSeatsRouteImport
      parentRoute: typeof CheckinRoute
    }
    '/checkin/review': {
      id: '/checkin/review'
      path: '/review'
      fullPath: '/checkin/review'
      preLoaderRoute: typeof CheckinReviewRouteImport
      parentRoute: typeof CheckinRoute
    }
    '/checkin/passengers': {
      id: '/checkin/passengers'
      path: '/passengers'
      fullPath: '/checkin/passengers'
      preLoaderRoute: typeof CheckinPassengersRouteImport
      parentRoute: typeof CheckinRoute
    }
    '/checkin/confirmation': {
      id: '/checkin/confirmation'
      path: '/confirmation'
      fullPath: '/checkin/confirmation'
      preLoaderRoute: typeof CheckinConfirmationRouteImport
      parentRoute: typeof CheckinRoute
    }
    '/checkin/addons': {
      id: '/checkin/addons'
      path: '/addons'
      fullPath: '/checkin/addons'
      preLoaderRoute: typeof CheckinAddonsRouteImport
      parentRoute: typeof CheckinRoute
    }
    '/auth/signup': {
      id: '/auth/signup'
      path: '/auth/signup'
      fullPath: '/auth/signup'
      preLoaderRoute: typeof AuthSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/pnr': {
      id: '/auth/pnr'
      path: '/auth/pnr'
      fullPath: '/auth/pnr'
      preLoaderRoute: typeof AuthPnrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/auth/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface CheckinRouteChildren {
  CheckinAddonsRoute: typeof CheckinAddonsRoute
  CheckinConfirmationRoute: typeof CheckinConfirmationRoute
  CheckinPassengersRoute: typeof CheckinPassengersRoute
  CheckinReviewRoute: typeof CheckinReviewRoute
  CheckinSeatsRoute: typeof CheckinSeatsRoute
  CheckinIndexRoute: typeof CheckinIndexRoute
}

const CheckinRouteChildren: CheckinRouteChildren = {
  CheckinAddonsRoute: CheckinAddonsRoute,
  CheckinConfirmationRoute: CheckinConfirmationRoute,
  CheckinPassengersRoute: CheckinPassengersRoute,
  CheckinReviewRoute: CheckinReviewRoute,
  CheckinSeatsRoute: CheckinSeatsRoute,
  CheckinIndexRoute: CheckinIndexRoute,
}

const CheckinRouteWithChildren =
  CheckinRoute._addFileChildren(CheckinRouteChildren)

interface DashboardRouteChildren {
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BoardingPassRoute: BoardingPassRoute,
  CheckinRoute: CheckinRouteWithChildren,
  DashboardRoute: DashboardRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  AuthForgotRoute: AuthForgotRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthPnrRoute: AuthPnrRoute,
  AuthSignupRoute: AuthSignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
